name: docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./.devcontainer/Dockerfile
      #     load: true
      #     # outputs: type=local,dest=./container.tar
      #     tags: dolfinx-dev-container
      - 
        name: Build Container
        working-directory: .devcontainer
        run: docker buildx build -t dolfinx-dev-container .
      -
        name: Test compile DolfinX in Container
        working-directory: .devcontainer
        run: docker exec -it dolfinx-dev-container ./.devcontainer/test_build.sh
